# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 
  jobs:
    - job:
      steps:
        - script: |
            mkdir prithvi && touch prithvi.txt
          displayName: "Creating Directory and text file"