# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build 
  jobs:
    - job:
      steps:
        - script: |
            mkdir prithvi && touch prithvi.txt
          displayName: "Creating Directory and text file"
- stage: Deploy
  condition: succeeded()
  jobs:
    - deployment:
      displayName:  Deploy
      environment: Prod
      strategy:
       runOnce:
         deploy:
           steps:
            - script: |
                  ls
          